### ISSUE TITLE
Fee rate used doesn't match fee rate for policy

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#3962]
I sent the following transaction: https://insight.bitpay.com/tx/a371234aaeb577f78cd83ef5393e458db6d65339a5f3b235a018d941d887dedf
when having the "Bitcoin Network Fee Policy" set to "Normal". The fee policy for Normal is currently b443/kb. Insight shows this transaction has a fee rate of b112.06 per kb.

Also, I noticed that switching between Economy, Normal, and Priority didn't change the transaction fee that was shown to me before confirming the transaction. I switched between the policy options to see if the fee would change but the fee remained the same.

**Comment by matiu** [comment]
We have deployed version 1.9.3 to stores that have some fixes related fee leves. Please let us know if it fix this problem.

**Comment by Jacobbubble** [comment]
@matiu Looks like the version in the Chrome store is still 1.9.2.
I'm assuming it takes 24 hours to update the version though. Will report back then + after some testing.


![screenshot from 2016-03-08 00-39-26](https://cloud.githubusercontent.com/assets/6015223/13596296/80e96bd8-e4c6-11e5-94ca-75f9296653e2.png)

**Comment by matiu** [comment]
I meant 1.9.2, sorry.

On Tue, Mar 8, 2016 at 5:42 AM, Jacob J Burrell <notifications@github.com>
wrote:

> @matiu <https://github.com/matiu> Looks like the version in the Chrome
> store is still 1.9.2.
> I'm assuming it takes 24 hours to update the version though. Will report
> back then + after some testing.
>
> [image: screenshot from 2016-03-08 00-39-26]
> <https://cloud.githubusercontent.com/assets/6015223/13596296/80e96bd8-e4c6-11e5-94ca-75f9296653e2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3962#issuecomment-193664735>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by Jacobbubble** [comment]
Tried again, the fee rate still doesn't match exactly.

Example: Transaction 307fd8e311810235e6c75a9f516651da361ca3eb8f94e5cc452e441b5e8b1db5 (https://insight.bitpay.com/tx/307fd8e311810235e6c75a9f516651da361ca3eb8f94e5cc452e441b5e8b1db5) shows the transaction as having a fee rate of "341.91 bits per kB" however I sent this transaction with a "Normal" policy, which has "Current fee rate for this policy:" set to 298 bits/kiB.

**Comment by KeyJockey** [comment]
I can confirm that the fee value shown in the fee preference setting does not match the actual miner fee that's put into the transaction.

This is yet another reason to consider that MINER FEE CONTROL in Copay needs to be significantly overhauled ASAP, hopefully for next version.  

And, for god's sake *please* finally include provision for *advanced* users to manually control exact fee.

See my proposal with screenshot images over on my https://github.com/bitpay/copay/issues/3111 thread...

**Comment by matiu** [comment]
@Jacobbubble That small deviations are expected, since the transaction size is estimated.

thanks a lot for the report.
