### ISSUE TITLE
CANNOT SEND TRANSACTION - SIGNATURE REJECTED BY SERVER

### ISSUE THREAD

**Issue by najmina** [bitpay/copay#4133]
I cannot send transaction since 18 hours ago.
Signature rejected by server.
 Please help me

**Comment by matiu** [comment]
Please see https://github.com/bitpay/copay/wiki/Signature-Rejected-by-the-Server-or-Cannot-verify-Server-Response

Provide the required information and we will try to help you.

**Comment by chaosgrid** [comment]
Same here. What is going on? It does not happen on my Chrome App, only on my Mobile (same wallet):

What platform (device) are you using?
Android 6.0.1

What Copay version are you using?
v1.11.0

What type of wallet is? (1-1 or multisig)
Normal (1-1)

When (approximately) the wallet was created?
1 year maybe?

Do you have mnemonic backups or file export?
File Export

Did you imported the wallet on your current device (or you created the wallet somewhere else and then you import it)?
I think I originally created it on Android.

I also tried re-importing from backup file but that did not get rid of the error.

**Comment by matiu** [comment]
@chaosgrid thanks for the information.

Copay derivation path changed in version 1.2.5, and we believe there could be a bug when importing old backups.

Did you try the recovery tool? Do you see your funds available there?

**Comment by chaosgrid** [comment]
I'm pretty certain this has nothing to do with the import mechanism. I can see my funds just fine on my mobile, I get notifications, everything works except sending money. I just did the following test:

I used my old Copay Win desktop app to import in the same way I did the re-import on mobile. The wallet was added fine there as well and I could also send transactions (v1.11.0).

Anyways, I think you have a major problem in your Android version or your server backend because I just tried to simply create a new wallet (simple normal 1-1 wallet with wallet seed). The wallet creation works fine but as soon as I want to display an address I get this:

![screenshot_20160426-203331](https://cloud.githubusercontent.com/assets/4355375/14830075/149b2a34-0bef-11e6-8365-52d86c34a194.png)

And the same happens on my malfunctioning wallet btw. I have a feeling the complete wallet functionality is broken in the current version on Android mobile!

**Comment by isocolsky** [comment]
We have detected some issues with Phillips phones. Could you please tell us brand and model of your device?

**Comment by chaosgrid** [comment]
Galaxy S6.

I just tried out my wallet on my old Galaxy S3 with Android 4.4 (Copay both v1.1.1 and v1.11.0) and it works without problems there. So maybe it is an issue either with the Galaxy S6 specifically or Android 6?

**Comment by chaosgrid** [comment]
I just did a reinstall and not even that fixed the problem with sending funds. Just a note on the problem with generating new addresses: This seems to be sporadic and not really consistent. I can now generate new addresses again but then again sometimes it fails.

Another note: When I make those failed send requests, I actually see the send proposal on the app on my other devices. If I then approve the transaction there it works. It just does not work at all on the GS6.

**Comment by chaosgrid** [comment]
And I just did another test. I reinstalled Copay again. Then, with the standard wallet that gets created at startup, I just sent it some bits. Then I tried to send those bits to another wallet of mine. Same error, so this has nothing to do with importing wallets it seems.

**Comment by chaosgrid** [comment]
And now it works!?!

I sincerely hope you fixed something on your backend because otherwise I feel like I'm going insane ;)

**Comment by matiu** [comment]
@chaosgrid no, no changes on the backend...

**Comment by matiu** [comment]
You can see Copay session logs  in settings > advanced > about copay > session logs

maybe there is some indication there?

also, JIC, be sure to try everything on the same network.

**Comment by chaosgrid** [comment]
I'm all the time on the same network here. And yeah, the error is back (just tried it again). There is nothing really useful in the session log. Is there any other way I could debug this?

**Comment by lclc** [comment]
I have the same problem:

What platform (device) are you using?
Nexus 5X, Android 6.0.1

What Copay version are you using?
1.11.0

What type of wallet is? (1-1 or multisig)
1-1

When (approximately) the wallet was created?
~ A week ago, But I haven't used it until today.

Do you have mnemonic backups or file export?
Should have mnemonic backup somewhere

Did you imported the wallet on your current device (or you created the wallet somewhere else and then you import it)?
No.


Trying to send 0.00221534 (1CHF) to 1FiroDvTrXmU8P8KpPqEVTo5byaVkg9X9o
0.000059 BTC fee (normal)

Error there: Payment was created but couldn't finish. Please try again in the home screen (freely translated from German).

When I press "Accept" in the transaction from the home screen it says Signature declined by the server.

**Comment by lclc** [comment]
Also the session log looks good (no failures or errors).

**Comment by braydonf** [comment]
@lclc I've seen this issue before, and it was because of trying to spend an unconfirmed transaction that the receiving backend bitcoind didn't have yet. Rebroadcasting, trying again later in about 10 min would confirm that. Also, this may be a different issue than what @chaosgrid is reporting.

**Comment by lclc** [comment]
@braydonf I have 26 confirmations for the funds I want to spend: 7b7de3151f9684ece300db58f5191ac82115b443bd8f9606a7006bd9a0c47c20

The error is the same, so it sounds related to me.

I can turn on adb to log later.

**Comment by matiu** [comment]
@lclc did you tried deleting the payment and trying to create a new one?

**Comment by lclc** [comment]
@matiu Yes, I tried that several times.

**Comment by matiu** [comment]
@lclc  Thanks. Could you please try the following?

Create a Spend proposal on your android device. And try to sign it. Once it fails, import your wallet on other device (an other phone or any desktop computer, using your mnemonic or wallet export (your can see your mnemonics or do an export in Wallet Settings)). And in the other device your should see the same transaction. Can you try to sign it there and let us know if it words?

Thanks a lot and sorry for the inconveniences. We are trying to reproduce this issue, with we could not do it yet.

**Comment by chaosgrid** [comment]
Just a little update here: I downgraded Copay to v1.10.2 and that one works. So whatever changed in the signing process between the two versions probably is the reason for the bug.

**Comment by matiu** [comment]
Thanks @chaosgrid Can you confirm it is working consistently on v1.10.2.  Changes from 1.11 to 1.10 where really small and mostly related to Coinbase integration.

**Comment by chaosgrid** [comment]
Yes, can confirm. Tried two more tx and both went through. As soon as I upgraded again to v1.11 it fails again. If you want, you can send me some more signed apks for me to test. Are there apks somewhere for 1.10.4 etc..?

**Comment by matiu** [comment]
Thanks a lot @chaosgrid 

We just added more logs in the server and we added to the client to send the rawTX also, so we can check we are signing the same thing.

Could you please try this version?

https://play.google.com/apps/testing/com.bitpay.copay

It is provided as a Play Store Open Beta Program. The APK is signed and distributed with the same procedures non-beta Copay use.

The version only add more logs so we can try to figure out that is the problem.

thanks a lot.

**Comment by chaosgrid** [comment]
So I got the beta version I think and tried to send a tx. Do I have to get the log or do you get it serverside?

**Comment by matiu** [comment]
@chaosgrid  we got it. Let us check it in detail and we will get back to you. Thanks a lot for all your help!

**Comment by matiu** [comment]
@chaosgrid we updated the beta with some client side logs. Could you please try to sign again and send me the phone logs to matias@bitpay.com ? thanks a lot.

**Comment by matiu** [comment]
@chaosgrid @lclc We have setup a test page for Copay's underlying bitcoin library (bitcore). could you please enter to this page with your device: http://matiu.com.ar/bitcore/test/index.html  There should only be some time out errors in tests, but other that it should pass all tests. Please let us know. thanks al ot.

**Comment by chaosgrid** [comment]
I'm not getting the new beta version via Google Play...

The test site, I just opened it with Chrome on my phone and everything passes except "Block" with "#from buffer" - but it's just a timeout.

**Comment by matiu** [comment]
@chaosgrid thanks. Ruling out bitcore-lib problems helps a lot.

The new bata version is:
Version code
838
 
Version name
1.11.1
 
Size
6.05 MB

(it does have the same 1.11.1 version name, but it has a different version code)

Are you able to install it?

**Comment by chaosgrid** [comment]
@matiu Where do I see the version code?
It just says v1.11.1 #dba5ecf
Also, which log should I send you? Just the session log? Btw. I noticed that the session log truncates log messages that are too long, even if you go for the "Send by Email" option...

**Comment by matiu** [comment]
Yes, session log.

I am just looking for the entries:

```
  log.debug('Signing ' + txp.inputs.length + ' inputs.');
```
and
```
  log.debug('Obtained ' + privs.length + ' private keys.');
```
and
```
  log.debug('Resulting raw signatures:', JSON.stringify(signatures));

```

thanks

**Comment by chaosgrid** [comment]
@matiu I think I still don't have the right version because I do not see that in my log. Could you upload the .apk somewhere so I can manually download it?

**Comment by matiu** [comment]
Let me do it again, and bump the version.

**Comment by matiu** [comment]
ok, it is BETA update. Version is v1.11.2

We are looking for an output similar to this one:

```
[api.js.1769:signTxProposal]
angular.js:26 [api.js.1792:signatures:] BEFORE undefined
angular.js:26 Signing 1 inputs.
angular.js:26 Obtained 1 private keys.
angular.js:26 Resulting raw signatures: [[{"publicKey":"02cf2ad2422227a961f72a9d62f226b9725bc8513397465d50b08f4d238df2336b","prevTxId":"6b4a990d9be8ee8bc3f843ccc9c7096af9ba9dae5c30b265b975ee7dd0698d1e","outputIndex":1,"inputIndex":0,"signature":"304402203eb064684148a5a29257f1bbeb604f615255ca8c3db3ac7c116c2678c567059702204adc34921c35916a498ed3cd1ddc6d9670a89c22332afc47fd730562c7a95198","sigtype":1}]]
```

**Comment by chaosgrid** [comment]
@matiu Sorry, so I just inspected the manifest file and it actually says version code 838 so it is apparently the correct version. I just sent you a log - but as said it did not contain the log messages you described.

**Comment by matiu** [comment]
Please try the one I just uploaded (1.11.2; version code 848) it has a little more info.

**Comment by lclc** [comment]
I didn't try with another device yet, but the tests you linked to where good (2 failed because time outs).

I should have time to test the Testing version tonight (CET).

**Comment by matiu** [comment]
Thanks @lclc  @chaosgrid  

we just release a new BETA (1.11.3) to try to identify the problem: 
https://play.google.com/apps/testing/com.bitpay.copay


Please send me (matias@bitpay.com) the logs after trying to sign.

We really appreciate all your help trying to solve this issue.

**Comment by matiu** [comment]
We think we have identified the problem...

Could you guys please try Beta 4
at:

https://play.google.com/apps/testing/com.bitpay.copay

and send me the log again?

thanks a lot.

@lclc @chaosgrid

**Comment by chaosgrid** [comment]
Beta 3 just gives me "Preparing to sign transaction" log message, nothing new otherwise as far as I could see. Now waiting for Google to stop bugging out and allowing me to get Beta 4... I really don't like the Google Beta program, it is not reliable at all :(

**Comment by matiu** [comment]
thanks. 

The latest one is:

Version code
868
 
Version name
1.11.4

**Comment by lclc** [comment]
Tried again with 1.1.5, same error. Sent you the log

**Comment by matiu** [comment]
Thanks @lclc

**Comment by matiu** [comment]
We tried to reproduce the error by buying a Android Nexus 5 device with Android 6, and getting one of the wallets that was generating the error, but unlucky the error did not show up, and we were able to sign transactions without problems.

 
We have published  BETA 10,  Version code 918, Version name 1.12.2 at
  https://play.google.com/apps/testing/com.bitpay.copay
with more logs in the signature part of Copay. Please if you are having this problem, download this beta, and send us the log to matias@bitpay.com

We need your help to fix this issue.
thanks a lot.

**Comment by TravellingGuy** [comment]
@matiu I just emailed a log from v. 1.12.2 to you where the "Signatures rejected by server" error happened.

**Comment by matiu** [comment]
Thanks a lot @TravellingGuy @lclc @chaosgrid you guys are awesome. We will find this bug.

**Comment by matiu** [comment]
@chaosgrid you mentioned you export / import the wallet, and the problem persists. Did you import  / export using mnemonic or using ' Advanced > Export' ?

**Comment by chaosgrid** [comment]
@matiu 

I actually switched to testing on testnet. For that, what I did was:

- create two wallets (1-1 each), both on testnet
- get btc from some faucet on one wallet
- try to send btc from that one wallet to the other

The error happens here as well and my latest logs I sent you are from those incidents. So I'm actually no longer doing any exports or imports and it still happens.

**Comment by matiu** [comment]
@chaosgrid Thanks.

Given it is a testnet wallet, Could you send me the export (Settings > Advanced > Export ) to matias@bitpay.com ? Just set the password to `1`.  If you can, leave an unsigned payment proposal pending.

Thanks a lot!

**Comment by matiu** [comment]
## Update:

We are still no able to reproduce the bug.  We tried on an Android 6 device (Nexus 5), with new wallets, and with wallet from testnet and livenet from users that reported the error, importing from mnemonic and export. So far no luck.

## What we know?
 - The error seems to be present only on Android 6 devices. No on all Android 6 devices. On the devices that present the error, Copay is sending EMPTY signatures to the server, so the signatures are rejected. We are sure it is not a problem with the wallet (wallet corruption) and it is not server side (Wallet can be exported and imported to other devices and it will work there).

## Work arounds:
 - Recover your funds from Copay's recovery tool: https://bitpay.github.io/copay-recovery/
 - OR install Copay and import your wallet in other device: We support desktop platforms, Chrome apps, IOS and WP also. See https://copay.io
 - OR Downgrade to Copay 1.10.x (reported by @chaosgrid )
 
## How can I help to fix this bug?

We are working hard to find the source of the error, but until we are able to reproduce it, we need your help. We have been releasing Copay BETA versions with incremented logs so you can try to sign a transactions and then send us the log.

We just release Copay BETA Version 1.12.3 (version code 928)  https://play.google.com/apps/testing/com.bitpay.copay

That will show details of the signing error on the messages show at the Send tab (in the red box).
Please try to sign a TX with that version and send us the contents of the error.

We really appreciate your help and patience.

**Comment by chaosgrid** [comment]
This is on trying to send a payment proposal: Could not accept payment: No enough signatures after flatten:m/0/0 Nr of inputs:1 Nr of derived privs:1 Signatures:

**Comment by TravellingGuy** [comment]
To everyone else having this issue, what are the details of your phone. Maybe we can find some similarities (like rooted, or custom ROM, or specific phone type) that will help Copay reproduce the issue.

I've got a Nexus 5X, rooted, running PureNexus ROM.

**Comment by matiu** [comment]
Thanks @TravellingGuy  / @chaosgrid @lclc for the screenshots.

So it seems that the derived extended private keys is not the required one to sign the proposals. The initial derivation ( usually `m/44'/0'/0'`) seems to fail and deliver a different result in these devices.

We just upload a new version of the BETA (1.12.6) that derives the xpriv in a slightly different manner and adds more log. We think this could be a small different in the Javascript implementations.

Please try 1.12.6 (code 958) at BETA at
https://play.google.com/apps/testing/com.bitpay.copay

and let us know. In case of failure, the xpriv will be printed on the screen. If that happends, and your are working on a Livenet important wallet, DO NOT share the screenshot here.

thanks a lot.

**Comment by TravellingGuy** [comment]
Just gave 1.12.6 a try and it still fails. The error is:

```
Could not accept payment: Error: Failed to derived the correct xPriv:xprivxxxxxxxxxxxxx
exxpected:xprivyyyyyyyyyy
Base Derivation Path:m/44'/0'/0'
```
The two xPriv are different in my case.

Would you like me to email the log to you as well, @matiu?

**Comment by eleuteromaniaco** [comment]
I believe I had this problem yesterday with someone with a Samsung Galaxy S7 Edge.

I recommended Copay to him a day before, then the guy came to my office asking for help with his money locked in that Copay. After reading here that beta versions were not solving the problem I tried to import his money in an already working Copay wallet of mine.

But importing his seed on my iOS Copay or OS X Copay didn't work, it said that the server was not authorizing it. The only way I had to import his money in my Copay was using the JSON backup option. Then with my iOS Copay I was able of sending the funds to another non-Copay wallet of him.

Sorry I don't have information about his Android version.

**Comment by eleuteromaniaco** [comment]
Other related problem is that I have a shared wallet with another Android Copay user. But his payment proposals are not signed because of this problem, so he creates proposals that can't be sent because adding my signature is not enough.

@matiu: he is Daniel, he told me you already have his phone details.

**Comment by matiu** [comment]
@eleuteromaniaco 
> But importing his seed on my iOS Copay or OS X Copay didn't work, it said that the server was not authorizing it. 

Was that a testnet wallet?

**Comment by eleuteromaniaco** [comment]
@matiu 

> Was that a testnet wallet?

No, regular wallet with 30 BTC in it (the user was really scared about the problem).

**Comment by matiu** [comment]
@eleuteromaniaco

>But importing his seed on my iOS Copay or OS X Copay didn't work, it said that the server was not 
> authorizing it. The only way I had to import his money in my Copay was using the JSON backup option. > Then with my iOS Copay I was able of sending the funds to another non-Copay wallet of him.

ok, that seems to be unrelated to this error please open a new ticket so we can check it further if you can provide details.

**Comment by matiu** [comment]
@TravellingGuy Can you try to create a testnet wallet and see if you can sign transactions from that wallet?  You can get testnet bitcoins from http://faucet.xeno-genesis.com/

**Comment by TravellingGuy** [comment]
@matiu I created a new testnet wallet in Copay. I then tried to send bitcoins from xeno-genesis to my testnet wallet address and I got an error on the faucet site, "chooseCoins: No solution found". Not sure if that's "expected" because of the problem with Copay or I'm not doing something correct.

Just for funsies, I also tried sending myself bitcoins from http://tpfaucet.appspot.com/ as well (to my testnet wallet) and when I submit the form, it just takes me a blank page, so I'm assuming it's hitting an error as well (just not displaying it).

**Comment by dabura667** [comment]
@TravellingGuy post the testnet address and I'll send some testnet coins

**Comment by TravellingGuy** [comment]
@dabura667, here is the testnet address: mrYKc2NYioXxbQSSRDdUh9QwBYS3h3BFvV

**Comment by matiu** [comment]
@TravellingGuy just sent you some.

**Comment by TravellingGuy** [comment]
@matiu and @dabura667, thanks I received the bitcoin.

I just tried to send a small amount of the testnet bitcoin to http://faucet.xeno-genesis.com/ and it failed. Here is the error:
> The payment was created but could not be completed. Please try again from home screen: Could not accept payment: Error: No signatures after getSignatures:Paths: m/0/0 | Nr of inputs:1 | Nr of derived privs:1 | Signatures: Base Derivation Path:m/44'/1'/0'

**Comment by matiu** [comment]
UPDATE:

Until we have a better understanding of the problem we have temporary remove support of Galaxy S6/7 and Nexus 5x, the devices that reported this error so far.

**Comment by TravellingGuy** [comment]
Just an FYI, I exported my wallet from my Nexus 5X and imported it into my g/f phone (Moto G, Android 5.1) and was able to send the money, so I'm good for now. But if you need me to do any more testing, I'd be more than happy, so please let me know.

**Comment by matiu** [comment]
Thanks a lot @TravellingGuy. could you contact me directly to matias@bitpay.com so we can ask you your help in case we need it?   BTW, the wallet you have imported, can you tell me when it was created? (I need to know if it was created on the 5X on Android 6 or on other device or before you upgraded to Android 6).

thanks.

**Comment by matiu** [comment]
We have released v1.12.8 (version code 978) to the BETA program at:

https://play.google.com/apps/testing/com.bitpay.copay

This version has two differences:
  - It was build on a complete different environment and hardware.
  - It has a key derivation test

Please, try the following

0)- Download the BETA version, Make sure it is version v1.12.8 (version can be seen in the sidebar of Copay).

1) Go to Wallet Settings > Advanced > Wallet Info. On the first row you will see the item:
 **"BETA: Android Key Derivation Test:"**
Please report the result of that test, along your device brand and model.

2) If Key derivation shows " OK, TEST PASSED", please create a  *NEW  WALLET* (Can be a Testnet wallet if you know what we are talking about). Send little coins to that wallet, and try to remove then by creating an output transaction.

Please report this also, along your device brand and model  **with the logs** (obtained from `Global Settings  > About Copay > Session Logs `). sent them to matias@bitpay.com

Thanks a lot.

**Comment by matiu** [comment]
PS: The v1.12.8 APK is also available at: https://github.com/bitpay/copay/releases/download/v1.12.1/Copay-BETA-v1.12.8-Android.apk

**Comment by matiu** [comment]
UPDATE:

We uploaded v1.12.11 to PRODUCTION at the Play Store, and disabled the Beta Version.

This new version will solve most (but not all) of the signing problems on Nexus 5x and Galaxy S6/7 phone.

Please if you still have issues signing. please contact me (matias@bitpay.com) and send you walletId (get it from Settings > Advanced > Wallet Info ).

We dont have a clear understanding yet of the source of the problem. HD Key derivation stop working on Cordoba 6 on these devices. We will investigate further.

thanks.

**Comment by lclc** [comment]
It seems to work now, using my Nexus 5X.

Did you add those devices back to the support list so I can uninstall the test version and install stable from the playstore again?

**Comment by matiu** [comment]
Yes, but we couldn't reproduce the error yet :(

Today we got a Nexus 5X, we tried with Android 6.0.0 and 6.0.1 and with the
multiple security patched it downloaded today, and we were not able to
reproduce the issue.

Do you have you device rooted?

On Fri, May 6, 2016 at 3:52 PM, Lucas Betschart <notifications@github.com>
wrote:

> It seems to work now, using my Nexus 5X.
>
> Did you add those devices back to the support list so I can uninstall the
> test version and install stable from the playstore again?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4133#issuecomment-217528095>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by lclc** [comment]
No, plain Android, not rooted.

Did you try with the first version we reported the problem with?

2016-05-06 21:18 GMT+02:00 Matias Alejo Garcia <notifications@github.com>:

**Comment by matiu** [comment]
fixed on Copay/Android version 1.20
